import React from 'react';
import { Bot, AlertTriangle, CheckCircle } from 'lucide-react';

interface AIContentBadgeProps {
  sourceType: 'pdf' | 'user_input' | 'org_upload' | 'ai_only';
  generatedBy: 'openai' | 'claude' | 'hybrid';
  confidenceScore: number;
  className?: string;
}

function AIContentBadge({ sourceType, generatedBy, confidenceScore, className = '' }: AIContentBadgeProps) {
  const getConfidenceIndicator = () => {
    if (confidenceScore >= 0.8) {
      return {
        icon: <CheckCircle className="h-4 w-4 text-green-600" />,
        text: 'High Confidence',
        color: 'bg-green-50 text-green-700 border-green-200'
      };
    } else if (confidenceScore >= 0.5) {
      return {
        icon: <Bot className="h-4 w-4 text-yellow-600" />,
        text: 'Moderate Confidence',
        color: 'bg-yellow-50 text-yellow-700 border-yellow-200'
      };
    } else {
      return {
        icon: <AlertTriangle className="h-4 w-4 text-red-600" />,
        text: 'Low Confidence',
        color: 'bg-red-50 text-red-700 border-red-200'
      };
    }
  };

  const indicator = getConfidenceIndicator();

  return (
    <div className={`inline-flex flex-wrap gap-2 text-xs ${className}`}>
      {/* AI Badge */}
      <span className="inline-flex items-center px-2 py-1 rounded-full bg-indigo-50 text-indigo-700 border border-indigo-200">
        <Bot className="h-3 w-3 mr-1" />
        Generated by Dhiva AI
      </span>

      {/* Source Type */}
      <span className="inline-flex items-center px-2 py-1 rounded-full bg-gray-50 text-gray-700 border border-gray-200">
        Source: {sourceType.split('_').map(word => word.charAt(0).toUpperCase() + word.slice(1)).join(' ')}
      </span>

      {/* Confidence Score */}
      <span 
        className={`inline-flex items-center px-2 py-1 rounded-full border ${indicator.color}`}
        title={`Confidence Score: ${Math.round(confidenceScore * 100)}%`}
      >
        {indicator.icon}
        <span className="ml-1">{indicator.text}</span>
      </span>

      {/* Tooltip */}
      <div className="group relative inline-block">
        <span className="cursor-help underline decoration-dotted">ℹ️</span>
        <div className="hidden group-hover:block absolute bottom-full left-1/2 transform -translate-x-1/2 w-64 p-2 mb-2 bg-gray-900 text-white text-xs rounded shadow-lg">
          This content was generated using Dhiva's AI model. Always verify sensitive content.
        </div>
      </div>
    </div>
  );
}

export default AIContentBadge;