import React from 'react';
import { useParams } from 'react-router-dom';
import { Mail } from 'lucide-react';

function LegalPages() {
  const { page } = useParams<{ page: string }>();

  const getContent = () => {
    switch (page) {
      case 'terms':
        return {
          title: 'Terms of Use',
          content: `Welcome to Dhiva — an AI-powered learning platform that helps you understand topics at your pace, on your terms.

Please read these Terms of Use carefully before using Dhiva's services via our website, email, WhatsApp, or any connected platform.

1. What You're Agreeing To
By signing up or using Dhiva, you agree to:
• These Terms of Use
• Our Privacy Policy
• Our AI Disclosure and Consent Notice (for creators/orgs)

If you don't agree, please don't use Dhiva.

2. Who Can Use Dhiva
• Anyone 13 years or older
• Organizations, communities, or individuals uploading their own learning content
• Creators who wish to publish microlearning content via Dhiva

If you're under 18, make sure you have permission from a parent or guardian.

3. How Dhiva Works
Dhiva uses AI to:
• Create and deliver microlearning content via email or WhatsApp
• Analyze PDFs, articles, and other inputs
• Adapt learning content based on your interactions
• Send automated learning nudges, recaps, and quizzes

We also allow you to upload documents, take a quiz, and personalize your learning schedule.

4. AI & Content Disclaimer
• Some content is generated using AI (like OpenAI or Claude)
• It may contain factual errors or hallucinations — we do our best to minimize this
• Do not rely on Dhiva for medical, legal, or financial advice
• You are responsible for how you use the information you receive

5. Your Content & Data
By uploading content (like PDFs or courses), you confirm that:
• You have the right to use and share it
• You give Dhiva permission to process it using AI to generate learning materials
• You won't upload anything illegal, hateful, or harmful
• You retain ownership of your content, but Dhiva may use it to create learning plans for you or your approved audience.

6. Respect the Platform
You agree not to:
• Spam, abuse, or harm the system
• Scrape, reverse engineer, or exploit Dhiva
• Violate any applicable laws
• Use Dhiva to create harmful, discriminatory, or deceptive content

7. Termination
We may suspend or terminate your account if:
• You violate these terms
• You upload or request prohibited content
• We are legally required to restrict your access

You can stop using Dhiva anytime.

8. Changes to These Terms
We may update these terms from time to time. We'll notify you via email or WhatsApp if anything important changes.`
        };
      case 'privacy':
        return {
          title: 'Privacy Policy',
          content: `1. What This Covers
This Privacy Policy explains how Dhiva collects, uses, and protects your information when you:
• Use our learning platform
• Upload learning content (like PDFs)
• Interact with our AI
• Receive messages via email or WhatsApp

2. What We Collect
We may collect the following types of data:
✅ Personal Info: Name, email address, WhatsApp number (for delivery)
✅ Learning Preferences: Frequency, pace, delivery channel
✅ Learning Activity: Quizzes answered, microlearnings sent, feedback
✅ Uploaded Content: PDFs, documents, topic inputs
✅ Device Info: Browser, IP, app usage logs (via analytics tools)

3. How We Use Your Data
Purpose:
• Send You Learning: Deliver microlearning via Email or WhatsApp
• Personalize Content: Adapt difficulty, pacing, and formats
• Improve Dhiva: Analyze what works and how to make it better
• Generate Learnings: Use AI models to create or summarize content
• Keep Dhiva Secure: Detect spam, abuse, or misuse

We never sell your data.

4. How We Store Your Data
We use:
• Supabase for secure database storage
• Gupshup / Twilio for WhatsApp messaging
• Resend / Sendgrid for email delivery
• OpenAI/Claude to generate content from your inputs

All partners comply with industry-standard security protocols.

5. How You Can Control Your Data
You can:
• Unsubscribe from WhatsApp/Email at any time
• Request deletion of your data by writing to team@dhiva.co
• Edit or pause your preferences in your profile

For creators/orgs: you may request content removal or visibility updates.

6. AI Content Notice
Some content delivered by Dhiva is generated by AI. We do our best to:
• Provide source references
• Flag low-confidence answers
• Adapt learning sequences as needed

Still, Dhiva is not a substitute for professional, legal, or medical advice.

7. Children's Privacy
Dhiva is not intended for users under 13.
If you're under 18, parental permission is advised.

8. Updates to This Policy
We may update this policy. You'll be notified via Email or WhatsApp if the changes are significant.`
        };
      case 'ai-disclosure':
        return {
          title: 'AI Disclosure & Consent Notice',
          content: `1. What You Should Know
Dhiva uses AI-powered systems (such as OpenAI and Claude) to generate:
• Learning summaries
• Quizzes
• Polls
• Feedback messages
• Learning paths

These are automatically generated based on your input and preferences.

2. AI May Make Mistakes
While we work hard to ensure safe and relevant output:
• AI content may sometimes include inaccuracies or hallucinations
• Dhiva is not a substitute for professional advice (medical, legal, academic, or financial)
• You should use your judgment and verify any critical content

3. Consent to Use of AI
By using Dhiva, you consent to:
• Having your input (including PDFs or text prompts) processed by AI
• Receiving content generated automatically from these systems
• Your learning path being adjusted based on your interactions

You may opt out of AI-powered content by writing to team@dhiva.co, though this may limit your experience.

4. For Creators & Organizations
If you upload content to Dhiva (e.g. PDFs, articles, courses):
• You confirm that you have the right to share and use this material
• You consent to Dhiva processing it using AI to generate learnings for you or your learners
• You understand that the AI-generated outputs are not exact replicas or summaries, but reinterpretations for learning purposes

5. Transparency & Trust
We're committed to:
• Using only reputable and secure AI models
• Labeling AI-generated content clearly
• Including source links where possible
• Regularly improving our safeguards`
        };
      default:
        return {
          title: '404 - Page Not Found',
          content: 'The requested legal page does not exist.'
        };
    }
  };

  const { title, content } = getContent();

  return (
    <div className="min-h-screen bg-gradient-to-b from-gray-50 to-white py-12">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8">
        <div className="max-w-3xl mx-auto">
          <h1 className="text-3xl font-bold text-gray-900 mb-8">{title}</h1>
          <div className="bg-white rounded-xl shadow-sm border border-gray-100 p-8">
            <div className="prose prose-indigo max-w-none">
              {content.split('\n\n').map((paragraph, index) => (
                <p key={index} className="mb-4 whitespace-pre-line">
                  {paragraph}
                </p>
              ))}
            </div>
          </div>
          <div className="mt-8 text-center text-gray-500">
            <p className="flex items-center justify-center">
              <Mail className="h-4 w-4 mr-2" />
              Contact us at: team@dhiva.co
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}

export default LegalPages;